package pe.gob.susalud.renipress.comun.util;

import java.io.Serializable;

import pe.gob.susalud.renipress.comun.util.Constantes.MENSAJE;

/***
 * @name      : MensajeForm - Clase que almacena los mensajes de error que se mostrará en pantalla
 * @author    : millesca
 * @version   : 1.0
 * @copyrigth : SUSALUD
 */
public class MensajeForm implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private String GENERAL_OK = MENSAJE.GENERAL_OK;
	private String GENERAL_CONFIRM = MENSAJE.GENERAL_CONFIRM;	
	private String GENERAL_ADD = MENSAJE.GENERAL_ADD;
	private String GENERAL_CANCEL = MENSAJE.GENERAL_CANCEL;
	private String GENERAL_FECHA = MENSAJE.GENERAL_FECHA;
	private String GENERAL_EMAIL = MENSAJE.GENERAL_EMAIL;
	private String GENERAL_TIPO_DOCUMENTO_ADJUNTO = MENSAJE.GENERAL_TIPO_DOCUMENTO_ADJUNTO;
	private String GENERAL_ERROR = MENSAJE.GENERAL_ERROR;
	private String GENERAL_DNI_LENGTH = MENSAJE.GENERAL_DNI_LENGTH;
	private String GENERAL_TIME = MENSAJE.GENERAL_TIME;
	/**
	 * MÓDULO DE CATEGORIZADOR
	 */		
	private String CATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR;
	
	// REGLAS POR CADA PROCESO . CATEGORIZADOR		
	private String CATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE;		
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE;	
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE;			
	// REGLAS POR CADA PROCESO . RENIEC
	private String CATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO;	
	private String CATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO;	
	private String CATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA;	
	private String CATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC;	
	private String CATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO;			
	// CATEGORIZADOR - CERTIFICADO - CATEGORIZADOR ESPECIALIZADO
	private String CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP;	
	private String CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP;	
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP;	
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP;
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY;	
	private String CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP;	
	// CATEGORIZADOR - CERTIFICADO - REGISTRADOR y CATEGORIZADOR	
	private String CATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA;	
	private String CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR;			
	private String CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION;	
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION;	
	private String CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR;	
	private String CATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION;	
	private String CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR;	
	private String CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD;	
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO;	
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA;
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY;
	private String CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO;	
	// CATEGORIZADOR - PERSONA
	private String CATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA;
	private String CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION = MENSAJE.CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU;
	/**
	 * LOGIN
	 */
	
	private String CATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA;
	private String CATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL = MENSAJE.CATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL;
	
	/**
	 * MÓDULO DE TAREA 
	 */
	private String TAREA_FORMMENSAJE_EMA_CORREOELECTRONICO = MENSAJE.TAREA_FORMMENSAJE_EMA_CORREOELECTRONICO;
	private String TAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO = MENSAJE.TAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO;
	
	private String TAREA_FORMMENSAJE_CMB_PROCESO = MENSAJE.TAREA_FORMMENSAJE_CMB_PROCESO;
	private String TAREA_FORMMENSAJE_CMB_TIPOTAREA = MENSAJE.TAREA_FORMMENSAJE_CMB_TIPOTAREA;
	private String TAREA_FORMMENSAJE_CMB_TAREATUPA = MENSAJE.TAREA_FORMMENSAJE_CMB_TAREATUPA;
	private String TAREA_FORMMENSAJE_CMB_TIPODIAS = MENSAJE.TAREA_FORMMENSAJE_CMB_TIPODIAS;
	private String TAREA_FORMMENSAJE_TXT_CANTIDADDIAS = MENSAJE.TAREA_FORMMENSAJE_TXT_CANTIDADDIAS;
	private String TAREA_FORMMENSAJE_TXT_DESCRIPCION = MENSAJE.TAREA_FORMMENSAJE_TXT_DESCRIPCION;
	private String TAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA = MENSAJE.TAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA;
	private String TAREA_FORMMENSAJE_CMB_ROLRESPONSABLE= MENSAJE.TAREA_FORMMENSAJE_CMB_ROLRESPONSABLE;
	private String TAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE= MENSAJE.TAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE;
	private String TAREA_FORMMENSAJE_TXT_MENSAJE = MENSAJE.TAREA_FORMMENSAJE_TXT_MENSAJE;
	private String TAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA = MENSAJE.TAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA;
	private String TAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO = MENSAJE.TAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO;
	private String TAREA_FORMMENSAJE_TXT_ASUNTO = MENSAJE.TAREA_FORMMENSAJE_TXT_ASUNTO;
	private String TAREA_FORMMENSAJE_TXT_MENSAJECORREO = MENSAJE.TAREA_FORMMENSAJE_TXT_MENSAJECORREO;
	private String TAREA_FORMMENSAJE_OK = MENSAJE.TAREA_FORMMENSAJE_OK;
	private String TAREA_FORMMENSAJE_GRILLA_ESTADO = MENSAJE.TAREA_FORMMENSAJE_GRILLA_ESTADO;
	
	/**
	 * MÓDULO EVALUACION DE SOLICITUD
	 */
	public static final String SOLICITUD_FORMMENSAJE_OK = MENSAJE.SOLICITUD_FORMMENSAJE_OK;
	
	/* VISITA */
	private String VISITA_FORM_GUARDAR_ERROR =  MENSAJE.VISITA_FORM_GUARDAR_ERROR;
	private String VISITA_FORM_FECHA_PROGRAMADA = MENSAJE.VISITA_FORM_FECHA_PROGRAMADA;
	
	private String VISITA_FORM_FECHA_INI_WITH = MENSAJE.VISITA_FORM_FECHA_INI_WITH;
	private String VISITA_FORM_FECHA_FIN_WITH = MENSAJE.VISITA_FORM_FECHA_FIN_WITH;
	private String VISITA_FORM_FECHA_RANGE	  = MENSAJE.VISITA_FORM_FECHA_RANGE;
	 
	/* OBSERVACION */
	
	private String OBSERVACION_TXT_OBSERVACION = MENSAJE.OBSERVACION_TXT_OBSERVACION;
	private String OBSERVACION_SEL_ESTADO = MENSAJE.OBSERVACION_SEL_ESTADO;
	
	
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR the cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR(
			String cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR) {
		CATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR = cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK_EDITAR;
	}
	/**
	 * @return the gENERAL_FECHA
	 */
	public String getGENERAL_FECHA() {
		return GENERAL_FECHA;
	}
	/**
	 * @param gENERAL_FECHA the gENERAL_FECHA to set
	 */
	public void setGENERAL_FECHA(String gENERAL_FECHA) {
		GENERAL_FECHA = gENERAL_FECHA;
	}
	/**
	 * @return the gENERAL_EMAIL
	 */
	public String getGENERAL_EMAIL() {
		return GENERAL_EMAIL;
	}
	/**
	 * @param gENERAL_EMAIL the gENERAL_EMAIL to set
	 */
	public void setGENERAL_EMAIL(String gENERAL_EMAIL) {
		GENERAL_EMAIL = gENERAL_EMAIL;
	}
	/**
	 * @return the gENERAL_TIPO_DOCUMENTO_ADJUNTO
	 */
	public String getGENERAL_TIPO_DOCUMENTO_ADJUNTO() {
		return GENERAL_TIPO_DOCUMENTO_ADJUNTO;
	}
	/**
	 * @param gENERAL_TIPO_DOCUMENTO_ADJUNTO the gENERAL_TIPO_DOCUMENTO_ADJUNTO to set
	 */
	public void setGENERAL_TIPO_DOCUMENTO_ADJUNTO(
			String gENERAL_TIPO_DOCUMENTO_ADJUNTO) {
		GENERAL_TIPO_DOCUMENTO_ADJUNTO = gENERAL_TIPO_DOCUMENTO_ADJUNTO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK the cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK(
			String cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK) {
		CATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK = cATEGORIZADOR_FORMCATEGORIZADOR_GUARDAR_OK;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE() {
		return CATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE the cATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE(
			String cATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE) {
		CATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE = cATEGORIZADOR_FORMCERTIFICACION_REGLA_CERTIFICADO_VIGENTE;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE = cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP_RANGE;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE the cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE = cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RANGE;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO() {
		return CATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO the cATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO(
			String cATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO) {
		CATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO = cATEGORIZADOR_FORMCERTIFICACION_REGLA_FECHA_NACIMIENTO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO() {
		return CATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO the cATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO(
			String cATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO) {
		CATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO = cATEGORIZADOR_FORMCERTIFICACION_REGLA_SEXO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA() {
		return CATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA the cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA(
			String cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA) {
		CATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA = cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_REGISTRADA;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC() {
		return CATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC the cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC(
			String cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC) {
		CATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC = cATEGORIZADOR_FORMCERTIFICACION_REGLA_PERSONA_NO_RENIEC;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO() {
		return CATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO the cATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO(
			String cATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO) {
		CATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO = cATEGORIZADOR_FORMCERTIFICACION_REGLA_NO_AGREGAR_CERTIFICADO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP() {
		return CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP(
			String cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP) {
		CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP = cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADOCUMENTOIDENTIDADESP;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP() {
		return CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP the cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP(
			String cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP) {
		CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP = cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITIDOSUSALUDESP;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP = cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADOESP;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP = cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP() {
		return CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP(
			String cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP) {
		CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP = cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADOESP;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA() {
		return CATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA the cATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA(
			String cATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA) {
		CATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA = cATEGORIZADOR_FORMCERTIFICACION_CMB_AUTORIDADSANITARIA;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR() {
		return CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR(
			String cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR) {
		CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR = cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIARESOLUCIONDESIGNACIONTITULAR;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION() {
		return CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION the cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION(
			String cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION) {
		CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION = cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERORESOLUCION;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION = cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONRESOLUCION;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR() {
		return CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR the cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR(
			String cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR) {
		CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR = cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMERODNITITULAR;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION() {
		return CATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION the cATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION(
			String cATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION) {
		CATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION = cATEGORIZADOR_FORMCERTIFICACION_TXT_EMISORRESOLUCION;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR() {
		return CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR(
			String cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR) {
		CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR = cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIADNITITULAR;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD() {
		return CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD the cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD(
			String cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD) {
		CATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD = cATEGORIZADOR_FORMCERTIFICACION_TXT_NUMEROCERTIFICADOEMITITOSUSALUD;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO = cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAEMISIONCERTIFICADO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA the cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA = cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO() {
		return CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO the cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO(
			String cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO) {
		CATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO = cATEGORIZADOR_FORMCERTIFICACION_FIL_COPIACERTIFICADO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD the cATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD(
			String cATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD) {
		CATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD = cATEGORIZADOR_FORMCATEGORIZADOR_CMB_TIPODOCUMENTOIDENTIDAD;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD(
			String cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD) {
		CATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD = cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NUMERODOCUMENTOIDENTIDAD;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA the cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA(
			String cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA) {
		CATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA = cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO the cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO(
			String cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO) {
		CATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO = cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO the cATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO(
			String cATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO) {
		CATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO = cATEGORIZADOR_FORMCATEGORIZADOR_CMB_SEXO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO(
			String cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO) {
		CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO = cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOPATERNO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO(
			String cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO) {
		CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO = cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOMATERNO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA(
			String cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA) {
		CATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA = cATEGORIZADOR_FORMCATEGORIZADOR_TXT_APELLIDOCASADA;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES(
			String cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES) {
		CATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES = cATEGORIZADOR_FORMCATEGORIZADOR_TXT_NOMBRES;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO the cATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO(
			String cATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO) {
		CATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO = cATEGORIZADOR_FORMCATEGORIZADOR_TXT_TELEFONO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA the cATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA(
			String cATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA) {
		CATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA = cATEGORIZADOR_FORMCATEGORIZADOR_EMA_CORREOELECTRONICOPERSONA;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA the cATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA(
			String cATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA) {
		CATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA = cATEGORIZADOR_FORMCATEGORIZADOR_DATABLE_GRILLA_EDITAR_GRILLA;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_EMA_CORREOELECTRONICO
	 */
	public String getTAREA_FORMMENSAJE_EMA_CORREOELECTRONICO() {
		return TAREA_FORMMENSAJE_EMA_CORREOELECTRONICO;
	}
	/**
	 * @param tAREA_FORMMENSAJE_EMA_CORREOELECTRONICO the tAREA_FORMMENSAJE_EMA_CORREOELECTRONICO to set
	 */
	public void setTAREA_FORMMENSAJE_EMA_CORREOELECTRONICO(
			String tAREA_FORMMENSAJE_EMA_CORREOELECTRONICO) {
		TAREA_FORMMENSAJE_EMA_CORREOELECTRONICO = tAREA_FORMMENSAJE_EMA_CORREOELECTRONICO;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_CMB_PROCESO
	 */
	public String getTAREA_FORMMENSAJE_CMB_PROCESO() {
		return TAREA_FORMMENSAJE_CMB_PROCESO;
	}
	/**
	 * @param tAREA_FORMMENSAJE_CMB_PROCESO the tAREA_FORMMENSAJE_CMB_PROCESO to set
	 */
	public void setTAREA_FORMMENSAJE_CMB_PROCESO(
			String tAREA_FORMMENSAJE_CMB_PROCESO) {
		TAREA_FORMMENSAJE_CMB_PROCESO = tAREA_FORMMENSAJE_CMB_PROCESO;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_CMB_TIPOTAREA
	 */
	public String getTAREA_FORMMENSAJE_CMB_TIPOTAREA() {
		return TAREA_FORMMENSAJE_CMB_TIPOTAREA;
	}
	/**
	 * @param tAREA_FORMMENSAJE_CMB_TIPOTAREA the tAREA_FORMMENSAJE_CMB_TIPOTAREA to set
	 */
	public void setTAREA_FORMMENSAJE_CMB_TIPOTAREA(
			String tAREA_FORMMENSAJE_CMB_TIPOTAREA) {
		TAREA_FORMMENSAJE_CMB_TIPOTAREA = tAREA_FORMMENSAJE_CMB_TIPOTAREA;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_CMB_TAREATUPA
	 */
	public String getTAREA_FORMMENSAJE_CMB_TAREATUPA() {
		return TAREA_FORMMENSAJE_CMB_TAREATUPA;
	}
	/**
	 * @param tAREA_FORMMENSAJE_CMB_TAREATUPA the tAREA_FORMMENSAJE_CMB_TAREATUPA to set
	 */
	public void setTAREA_FORMMENSAJE_CMB_TAREATUPA(
			String tAREA_FORMMENSAJE_CMB_TAREATUPA) {
		TAREA_FORMMENSAJE_CMB_TAREATUPA = tAREA_FORMMENSAJE_CMB_TAREATUPA;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_CMB_TIPODIAS
	 */
	public String getTAREA_FORMMENSAJE_CMB_TIPODIAS() {
		return TAREA_FORMMENSAJE_CMB_TIPODIAS;
	}
	/**
	 * @param tAREA_FORMMENSAJE_CMB_TIPODIAS the tAREA_FORMMENSAJE_CMB_TIPODIAS to set
	 */
	public void setTAREA_FORMMENSAJE_CMB_TIPODIAS(
			String tAREA_FORMMENSAJE_CMB_TIPODIAS) {
		TAREA_FORMMENSAJE_CMB_TIPODIAS = tAREA_FORMMENSAJE_CMB_TIPODIAS;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_TXT_CANTIDADDIAS
	 */
	public String getTAREA_FORMMENSAJE_TXT_CANTIDADDIAS() {
		return TAREA_FORMMENSAJE_TXT_CANTIDADDIAS;
	}
	/**
	 * @param tAREA_FORMMENSAJE_TXT_CANTIDADDIAS the tAREA_FORMMENSAJE_TXT_CANTIDADDIAS to set
	 */
	public void setTAREA_FORMMENSAJE_TXT_CANTIDADDIAS(
			String tAREA_FORMMENSAJE_TXT_CANTIDADDIAS) {
		TAREA_FORMMENSAJE_TXT_CANTIDADDIAS = tAREA_FORMMENSAJE_TXT_CANTIDADDIAS;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_TXT_DESCRIPCION
	 */
	public String getTAREA_FORMMENSAJE_TXT_DESCRIPCION() {
		return TAREA_FORMMENSAJE_TXT_DESCRIPCION;
	}
	/**
	 * @param tAREA_FORMMENSAJE_TXT_DESCRIPCION the tAREA_FORMMENSAJE_TXT_DESCRIPCION to set
	 */
	public void setTAREA_FORMMENSAJE_TXT_DESCRIPCION(
			String tAREA_FORMMENSAJE_TXT_DESCRIPCION) {
		TAREA_FORMMENSAJE_TXT_DESCRIPCION = tAREA_FORMMENSAJE_TXT_DESCRIPCION;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA
	 */
	public String getTAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA() {
		return TAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA;
	}
	/**
	 * @param tAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA the tAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA to set
	 */
	public void setTAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA(
			String tAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA) {
		TAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA = tAREA_FORMMENSAJE_CMB_AUTORIDADSANITARIA;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_CMB_ROLRESPONSABLE
	 */
	public String getTAREA_FORMMENSAJE_CMB_ROLRESPONSABLE() {
		return TAREA_FORMMENSAJE_CMB_ROLRESPONSABLE;
	}
	/**
	 * @param tAREA_FORMMENSAJE_CMB_ROLRESPONSABLE the tAREA_FORMMENSAJE_CMB_ROLRESPONSABLE to set
	 */
	public void setTAREA_FORMMENSAJE_CMB_ROLRESPONSABLE(
			String tAREA_FORMMENSAJE_CMB_ROLRESPONSABLE) {
		TAREA_FORMMENSAJE_CMB_ROLRESPONSABLE = tAREA_FORMMENSAJE_CMB_ROLRESPONSABLE;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE
	 */
	public String getTAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE() {
		return TAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE;
	}
	/**
	 * @param tAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE the tAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE to set
	 */
	public void setTAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE(
			String tAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE) {
		TAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE = tAREA_FORMMENSAJE_GRILLA_TAREA_PRECEDENTE;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_TXT_MENSAJE
	 */
	public String getTAREA_FORMMENSAJE_TXT_MENSAJE() {
		return TAREA_FORMMENSAJE_TXT_MENSAJE;
	}
	/**
	 * @param tAREA_FORMMENSAJE_TXT_MENSAJE the tAREA_FORMMENSAJE_TXT_MENSAJE to set
	 */
	public void setTAREA_FORMMENSAJE_TXT_MENSAJE(
			String tAREA_FORMMENSAJE_TXT_MENSAJE) {
		TAREA_FORMMENSAJE_TXT_MENSAJE = tAREA_FORMMENSAJE_TXT_MENSAJE;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA
	 */
	public String getTAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA() {
		return TAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA;
	}
	/**
	 * @param tAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA the tAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA to set
	 */
	public void setTAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA(
			String tAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA) {
		TAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA = tAREA_FORMMENSAJE_TXT_NUMERODIASPREVIOSALERTA;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO
	 */
	public String getTAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO() {
		return TAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO;
	}
	/**
	 * @param tAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO the tAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO to set
	 */
	public void setTAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO(
			String tAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO) {
		TAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO = tAREA_FORMMENSAJE_GRILLA_CORREOELECTRONICO;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_TXT_ASUNTO
	 */
	public String getTAREA_FORMMENSAJE_TXT_ASUNTO() {
		return TAREA_FORMMENSAJE_TXT_ASUNTO;
	}
	/**
	 * @param tAREA_FORMMENSAJE_TXT_ASUNTO the tAREA_FORMMENSAJE_TXT_ASUNTO to set
	 */
	public void setTAREA_FORMMENSAJE_TXT_ASUNTO(String tAREA_FORMMENSAJE_TXT_ASUNTO) {
		TAREA_FORMMENSAJE_TXT_ASUNTO = tAREA_FORMMENSAJE_TXT_ASUNTO;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_TXT_MENSAJECORREO
	 */
	public String getTAREA_FORMMENSAJE_TXT_MENSAJECORREO() {
		return TAREA_FORMMENSAJE_TXT_MENSAJECORREO;
	}
	/**
	 * @param tAREA_FORMMENSAJE_TXT_MENSAJECORREO the tAREA_FORMMENSAJE_TXT_MENSAJECORREO to set
	 */
	public void setTAREA_FORMMENSAJE_TXT_MENSAJECORREO(
			String tAREA_FORMMENSAJE_TXT_MENSAJECORREO) {
		TAREA_FORMMENSAJE_TXT_MENSAJECORREO = tAREA_FORMMENSAJE_TXT_MENSAJECORREO;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_OK
	 */
	public String getTAREA_FORMMENSAJE_OK() {
		return TAREA_FORMMENSAJE_OK;
	}
	/**
	 * @param tAREA_FORMMENSAJE_OK the tAREA_FORMMENSAJE_OK to set
	 */
	public void setTAREA_FORMMENSAJE_OK(String tAREA_FORMMENSAJE_OK) {
		TAREA_FORMMENSAJE_OK = tAREA_FORMMENSAJE_OK;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW the cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW(
			String cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW) {
		CATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW = cATEGORIZADOR_FORMCATEGORIZADOR_DAT_FECHANACIMIENTO_NOW;
	}
	/**
	 * @return the gENERAL_ERROR
	 */
	public String getGENERAL_ERROR() {
		return GENERAL_ERROR;
	}
	/**
	 * @param gENERAL_ERROR the gENERAL_ERROR to set
	 */
	public void setGENERAL_ERROR(String gENERAL_ERROR) {
		GENERAL_ERROR = gENERAL_ERROR;
	}
	/**
	 * @return the gENERAL_DNI_LENGTH
	 */
	public String getGENERAL_DNI_LENGTH() {
		return GENERAL_DNI_LENGTH;
	}
	/**
	 * @param gENERAL_DNI_LENGTH the gENERAL_DNI_LENGTH to set
	 */
	public void setGENERAL_DNI_LENGTH(String gENERAL_DNI_LENGTH) {
		GENERAL_DNI_LENGTH = gENERAL_DNI_LENGTH;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY the cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY = cATEGORIZADOR_FORMCERTIFICACION_DAT_FECHAVIGENCIAESP_MAY;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY the cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY = cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_MAY;
	}
	/**
	 * @return the gENERAL_OK
	 */
	public String getGENERAL_OK() {
		return GENERAL_OK;
	}
	/**
	 * @param gENERAL_OK the gENERAL_OK to set
	 */
	public void setGENERAL_OK(String gENERAL_OK) {
		GENERAL_OK = gENERAL_OK;
	}
	/**
	 * @return the gENERAL_CANCEL
	 */
	public String getGENERAL_CANCEL() {
		return GENERAL_CANCEL;
	}
	/**
	 * @param gENERAL_CANCEL the gENERAL_CANCEL to set
	 */
	public void setGENERAL_CANCEL(String gENERAL_CANCEL) {
		GENERAL_CANCEL = gENERAL_CANCEL;
	}
	/**
	 * @return the gENERAL_CONFIRM
	 */
	public String getGENERAL_CONFIRM() {
		return GENERAL_CONFIRM;
	}
	/**
	 * @param gENERAL_CONFIRM the gENERAL_CONFIRM to set
	 */
	public void setGENERAL_CONFIRM(String gENERAL_CONFIRM) {
		GENERAL_CONFIRM = gENERAL_CONFIRM;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_GRILLA_ESTADO
	 */
	public String getTAREA_FORMMENSAJE_GRILLA_ESTADO() {
		return TAREA_FORMMENSAJE_GRILLA_ESTADO;
	}
	/**
	 * @param tAREA_FORMMENSAJE_GRILLA_ESTADO the tAREA_FORMMENSAJE_GRILLA_ESTADO to set
	 */
	public void setTAREA_FORMMENSAJE_GRILLA_ESTADO(
			String tAREA_FORMMENSAJE_GRILLA_ESTADO) {
		TAREA_FORMMENSAJE_GRILLA_ESTADO = tAREA_FORMMENSAJE_GRILLA_ESTADO;
	}
	/**
	 * @return the tAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO
	 */
	public String getTAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO() {
		return TAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO;
	}
	/**
	 * @param tAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO the tAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO to set
	 */
	public void setTAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO(
			String tAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO) {
		TAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO = tAREA_FORMMENSAJE_REGLA_CANT_CORREO_ELECTRONICO;
	}
	/**
	 * @return the gENERAL_ADD
	 */
	public String getGENERAL_ADD() {
		return GENERAL_ADD;
	}
	/**
	 * @param gENERAL_ADD the gENERAL_ADD to set
	 */
	public void setGENERAL_ADD(String gENERAL_ADD) {
		GENERAL_ADD = gENERAL_ADD;
	}
	/**
	 * @return the vISITA_FORM_GUARDAR_ERROR
	 */
	public String getVISITA_FORM_GUARDAR_ERROR() {
		return VISITA_FORM_GUARDAR_ERROR;
	}
	/**
	 * @return the vISITA_FORM_FECHA_PROGRAMADA
	 */
	public String getVISITA_FORM_FECHA_PROGRAMADA() {
		return VISITA_FORM_FECHA_PROGRAMADA;
	}
	/**
	 * @return the vISITA_FORM_FECHA_INI_WITH
	 */
	public String getVISITA_FORM_FECHA_INI_WITH() {
		return VISITA_FORM_FECHA_INI_WITH;
	}
	/**
	 * @return the vISITA_FORM_FECHA_FIN_WITH
	 */
	public String getVISITA_FORM_FECHA_FIN_WITH() {
		return VISITA_FORM_FECHA_FIN_WITH;
	}
	/**
	 * @return the vISITA_FORM_FECHA_RANGE
	 */
	public String getVISITA_FORM_FECHA_RANGE() {
		return VISITA_FORM_FECHA_RANGE;
	}
	/**
	 * @return the oBSERVACION_TXT_OBSERVACION
	 */
	public String getOBSERVACION_TXT_OBSERVACION() {
		return OBSERVACION_TXT_OBSERVACION;
	}
	/**
	 * @param oBSERVACION_TXT_OBSERVACION the oBSERVACION_TXT_OBSERVACION to set
	 */
	public void setOBSERVACION_TXT_OBSERVACION(String oBSERVACION_TXT_OBSERVACION) {
		OBSERVACION_TXT_OBSERVACION = oBSERVACION_TXT_OBSERVACION;
	}
	/**
	 * @return the oBSERVACION_SEL_ESTADO
	 */
	public String getOBSERVACION_SEL_ESTADO() {
		return OBSERVACION_SEL_ESTADO;
	}
	/**
	 * @param oBSERVACION_SEL_ESTADO the oBSERVACION_SEL_ESTADO to set
	 */
	public void setOBSERVACION_SEL_ESTADO(String oBSERVACION_SEL_ESTADO) {
		OBSERVACION_SEL_ESTADO = oBSERVACION_SEL_ESTADO;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA the cATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA(
			String cATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA) {
		CATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA = cATEGORIZADOR_FORMCATEGORIZADOR_EMA_RE_CORREOELECTRONICOPERSONA;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL the cATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL(
			String cATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL) {
		CATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL = cATEGORIZADOR_FORMCATEGORIZADOR_TIPO_PERFIL;
	}
	/**
	 * @return the gENERAL_TIME
	 */
	public String getGENERAL_TIME() {
		return GENERAL_TIME;
	}
	/**
	 * @param gENERAL_TIME the gENERAL_TIME to set
	 */
	public void setGENERAL_TIME(String gENERAL_TIME) {
		GENERAL_TIME = gENERAL_TIME;
	}
	public static String getSOLICITUD_FORMMENSAJE_OK() {
		return SOLICITUD_FORMMENSAJE_OK;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION
	 */
	public String getCATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION() {
		return CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION;
	}
	/**
	 * @param cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION the cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION to set
	 */
	public void setCATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION(
			String cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION) {
		CATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION = cATEGORIZADOR_FORMCERTIFICACION_DAT_FINVIGENCIA_RESOLUCION;
	}
	/**
	 * @return the cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU
	 */
	public String getCATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU() {
		return CATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU;
	}
	/**
	 * @param cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU the cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU to set
	 */
	public void setCATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU(
			String cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU) {
		CATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU = cATEGORIZADOR_FORMCATEGORIZADOR_CMB_PAISPROCEDENCIA_PERU;
	}
	
	
}